GET http://localhost:5226/games

###
GET http://localhost:5226/games/3

###
POST http://localhost:5226/games
Content-Type: application/json

{
    "name": "Read Dead Redemption",
    "genreId": 2,
    "price": 69.99,
    "releaseDate": "2020-07-16"
}

###
PUT http://localhost:5226/games/3
Content-Type: application/json

{
    "name": "Minecraft 2",
    "genreId": 5,
    "price": 39.99,
    "releaseDate": "2022-07-28"
}

###
DELETE http://localhost:5226/games/5