GET http://localhost:5226/games

###
GET http://localhost:5226/games/4

###
POST http://localhost:5226/games
Content-Type: application/json

{
    "name": "Minecraft",
    "genreId": 5,
    "price": 19.99,
    "releaseDate": "2011-11-18"
}

###
PUT http://localhost:5226/games/3
Content-Type: application/json

{
    "name": "Hogwart Legacy",
    "genre": "Fantasy",
    "price": 29.99,
    "releaseDate": "2020-02-11"
}

###
DELETE http://localhost:5226/games/4